# Generated by Django 3.2.8 on 2021-11-03 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(default='#ffffff', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('altoTotal', models.FloatField()),
                ('anchoTotal', models.FloatField()),
                ('altoLamina', models.FloatField()),
                ('anchoLamina', models.FloatField()),
                ('precio', models.FloatField()),
                ('idColor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualizador3D.color')),
                ('idTipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualizador3D.tipo')),
            ],
        ),
    ]
