# Generated by Django 3.2.8 on 2021-11-03 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizador3D', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuadro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('altoTotal', models.FloatField()),
                ('anchoTotal', models.FloatField()),
                ('altoLamina', models.FloatField()),
                ('anchoLamina', models.FloatField()),
                ('precio', models.FloatField()),
                ('img', models.CharField(max_length=200)),
                ('idColor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualizador3D.color')),
            ],
        ),
        migrations.AddField(
            model_name='tipo',
            name='icono',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Piece',
        ),
        migrations.AddField(
            model_name='cuadro',
            name='idTipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualizador3D.tipo'),
        ),
    ]
