# Generated by Django 3.2.5 on 2021-11-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizador3D', '0003_auto_20211104_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadro',
            name='fichero3D',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
